use_frameworks!

platform :ios, '9.0'

target 'WXNSDK8_Example' do
  pod 'WXNSDK8', :path => '../'

  target 'WXNSDK8_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
